services:
  - name: spark
    type: local_spark
storage:
  vault: spark
  star: spark
  logs: azure_queue
compute: spark
storage_account_name: $AZURE_STORAGE_ACCOUNT
storage_account_key: $AZURE_STORAGE_KEY
secret_lookup: environment
