name: airport_details_allcaps
type: satellite
parent:
  name: airport
  type: hub
columns:
  "allcaps_name": {"type": "varchar(64)", "nullable": True}
pipeline:
  type: sql
  key_columns:
    "airport": "hub_airport_key"
  dependencies:
    - type: satellite
      name: airport_details
  load_dt: "sat_load_dt"
  deleted_ind: "sat_deleted_ind"
  sql: |
    SELECT

      hub_airport_key,
      UPPER(name) AS allcaps_name,
      sat_load_dt,
      sat_deleted_ind

    FROM {{satellite.airport_details.updates}} AS airport_details
