name: airport_pair_direct_flight
type: satellite
parent:
  name: airport_pair
  type: link
columns:
  "direct_flight": {"type": "char(1)", "nullable": True}
pipeline:
  type: sql
  key_columns:
    "dep_airport": "hub_dep_airport_key"
    "arr_airport": "hub_arr_airport_key"
  dependencies:
    - type: satellite
      name: airport_pair_details
  load_dt: "sat_load_dt"
  deleted_ind: "sat_deleted_ind"
  sql: |
    SELECT

      hub_dep_airport_key,
      hub_arr_airport_key,
      CASE
        WHEN num_changes = 0 THEN 1
        WHEN num_changes > 0 THEN 0
      END AS direct_flight,
      sat_load_dt,
      sat_deleted_ind

    FROM {{satellite.airport_pair_details.updates}} AS airport_pair_details
