name: last_updated_pair
type: satellite
parent:
  name: airport_pair
  type: link
columns:
  "last_updated_pair": {"type": "char(1)"}
pipeline:
  type: sql
  key_columns:
    "dep_airport": "hub_dep_airport_key"
    "arr_airport": "hub_arr_airport_key"
  dependencies:
    - type: satellite
      name: airport_pair_details
      view: current
  load_dt: "sat_load_dt"
  deleted_ind: "sat_deleted_ind"
  sql: |
    SELECT COALESCE(updates.hub_dep_airport_key,
                    now.hub_dep_airport_key) AS hub_dep_airport_key,
           COALESCE(updates.hub_arr_airport_key,
                    now.hub_arr_airport_key) AS hub_arr_airport_key,
           CASE WHEN updates.link_airport_pair_key IS NULL
                THEN 0
                ELSE 1
              END AS last_updated_pair,
           CURRENT_TIMESTAMP AS sat_load_dt,
           COALESCE(updates.sat_deleted_ind,
                    now.sat_deleted_ind) AS sat_deleted_ind

     FROM {{satellite.airport_pair_details.current}} AS now
          FULL JOIN {{satellite.airport_pair_details.updates}} AS updates
                 ON updates.link_airport_pair_key
                  = now.link_airport_pair_key
